Practice Web Scrapping

Lets import relevant libraries

In [3]:
from bs4 import BeautifulSoup
import requests
import csv
import pandas as pd

Practice website

In [65]:
# Practice website scrapping
url = "https://books.toscrape.com"
response = requests.get(url)

print(response.status_code) # Check if the request was successful (200 means OK)

200

In [66]:
soup = BeautifulSoup(response.text , "html.parser") # Create a BeautifulSoup object
books= soup.find_all("article", class_= "product_pod") 
for book in books:
    title = book.h3.a["title"]
    price = book.find("p",class_="price_color").text
    print(f"{title} - {price}")

A Light in the Attic - Â£51.77
Tipping the Velvet - Â£53.74
Soumission - Â£50.10
Sharp Objects - Â£47.82
Sapiens: A Brief History of Humankind - Â£54.23
The Requiem Red - Â£22.65
The Dirty Little Secrets of Getting Your Dream Job - Â£33.34
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull - Â£17.93
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics - Â£22.60
The Black Maria - Â£52.15
Starving Hearts (Triangular Trade Trilogy, #1) - Â£13.99
Shakespeare's Sonnets - Â£20.66
Set Me Free - Â£17.46
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) - Â£52.29
Rip it Up and Start Again - Â£35.02
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 - Â£57.25
Olio - Â£23.88
Mesaerion: The Best Science Fiction Stories 1800-1849 - Â£37.59
Libertarianism for Beginners - Â£51.33
It's Only the Himalayas - Â£45.17

In [67]:
#saving
with open("books.csv" , "w" , newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["title", "price"])
    for book in books:
     title = book.h3.a["title"]
     price = book.find("p",class_="price_color").text
     writer.writerow([title, price])

Lets start with our website - draft

In [68]:
#lets try
url = "https://www.iisermohali.ac.in/people"
response = requests.get(url)
print(response.status_code)

200

In [69]:
soup = BeautifulSoup(response.text, 'html.parser')
print(soup.title)
faculty = soup.find(string="FACULTY")
print(faculty)

<title>People</title>
FACULTY

In [70]:
tables = soup.find_all("table")
print(len(tables))
for i , table in enumerate(tables):
    print(f"Table {i+1}:")
    print(table)
    print("\n")

# we get an idea about how many tables are there and which one we want to scrap. We can use the index of the table to select the desired table.

18
Table 1:
<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 85.9676%; height: 45px;">
<tbody>
<tr style="height: 45px;">
<td style="width: 0.0897679%; height: 45px;"> </td>
<td style="width: 10.4131%; height: 45px;"><a href="https://www.iisermohali.ac.in/"><img height="115" src="/images/siteimages/logo/iiserlogo/iisermlogo_trans3.png" width="115"/></a></td>
<td style="width: 58.7105%; height: 45px;"><a href="https://www.iisermohali.ac.in/"><img height="161" src="/images/siteimages/logo/iiserlogo/Image_TextWeb.png" width="640"/></a></td>
<td style="width: 9.5131%; text-align: left;"> </td>
<td style="width: 5.2963%; text-align: left; height: 40px;"><a href="https://www.iisermohali.ac.in"><img height="40" src="/images/siteimages/logo/iiserlogo/homeicon.png" style="float: right;" width="40"/></a></td>
<td style="width: 5.2963%; text-align: left; height: 40px;"><a href="https://www.facebook.com/iisermohaliofficialpage/" rel="noopener" target="_blank"><img height="40" src="/images/siteimages/logo/socialmedia/facebook.png" style="float: right;" width="40"/></a></td>
<td style="width: 5.2963%; text-align: left; height: 40px;"><a href="https://twitter.com/iisermohali" rel="noopener" target="_blank"><img height="40" src="/images/siteimages/logo/socialmedia/twitter1.png" style="float: right;" width="40"/></a></td>
<td style="width: 5.2963%; text-align: left; height: 40px;"><a href="https://www.youtube.com/c/IISERMohaliOfficialChannel" rel="noopener" target="_blank"><img height="40" src="/images/siteimages/logo/socialmedia/youtube.png" style="float: right;" width="40"/></a></td>
<td style="width: 0.0897679%; text-align: left; height: 45px;"> </td>
</tr>
</tbody>
</table>


Table 2:
<table border="0" cellpadding="4" cellspacing="4" style="border-collapse: collapse; width: 40.2317%; height: 21.9097px; float: left;">
<tbody>
<tr style="height: 21.9097px;">
<td style="width: 19.6154%; height: 21.9097px; background-color: rgb(230, 126, 35); text-align: center;"><span style="font-size: 14px;"><strong><span style="color: #000000;"><a href="/nirf-2" style="color: #000000;">NIRF</a></span></strong></span></td>
<td style="width: 17.6779%; background-color: rgb(241, 196, 15); text-align: center;"><a href="/giving-to-iiser-mohali"><span style="font-size: 14px;"><strong><span style="color: #000000;">Giving</span></strong></span></a></td>
<td style="width: 11.7452%; height: 21.9097px; background-color: rgb(45, 194, 107); text-align: center;"><span style="font-size: 14px;"><strong><span style="color: #000000;"><a href="/rti" style="color: #000000;">RTI</a></span></strong></span></td>
<td style="width: 17.1154%; height: 21.9097px; background-color: rgb(53, 152, 219); text-align: center;"><span style="font-size: 14px;"><strong><span style="color: #000000;"><a href="https://web.iisermohali.ac.in/tenders/tenderinvite/" rel="noopener" style="color: #000000;" target="_blank">Tenders</a></span></strong></span></td>
<td style="width: 12.6923%; height: 21.9097px; background-color: rgb(203, 109, 81); text-align: center;"><span style="font-size: 14px;"><strong><span style="color: #000000;"><a href="/careers" style="color: #000000;">Careers</a></span></strong></span></td>
<td style="width: 21.1538%; height: 21.9097px; background-color: rgb(191, 237, 210); text-align: center;"><span style="font-size: 14px;"><strong><span style="color: #000000;"><a href="/announcements" style="color: #000000;">Announcements</a></span></strong></span></td>
</tr>
</tbody>
</table>


Table 3:
<table border="0" style="border-collapse: collapse; height: 58px;">
<tbody>
<tr>
<td style="width: 10%;"><img height="50" src="/images/siteimages/logo/icons/searchicon.gif" width="50"/></td>
<td><span style="font-size: 18px;"><a href="/people/faculty-search"><span style="text-decoration: underline;"><strong>FACULTY</strong> <strong>DIRECTORY SEARCH</strong></span></a></span></td>
</tr>
</tbody>
</table>


Table 4:
<table class="factable" id="facultytable" style="border-collapse: collapse; width: 100%;">
<thead>
<tr>
<th align="left">Name</th>
<th align="left">Department</th>
<th align="left">Designation</th>
<th align="left">Email</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left"><a href="/faculty/dms/aganguli">Abhik Ganguli</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">aganguli</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/abhishek">Abhishek Chaudhuri</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">abhishek</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/adrene">Adrene Freeda Dcruz</a></td>
<td align="left">HSS</td>
<td align="left">Associate Professor</td>
<td align="left">adrene</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/maharana">Alok Maharana</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">maharana</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/ashivaji">Ambresh Shivaji</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">ashivaji</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/amardeep">Amar Deep</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">amardeep</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/amitk">Amit Kulshrestha</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">amitk</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/ananthv">Ananth Venkatesan</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">ananthv</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/angshurc">Angshuman Roy Choudhury</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">angshurc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/adasanna">Anil Kumar Dasanna</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">adasanna</td>
</tr>
<tr>
<td style="width: 31.5199%; height: 52.7969px;"><a href="/faculty/dbs/aniltripathi">Anil Kumar Tripathi</a></td>
<td style="width: 19.5177%; height: 52.7969px;">DBS</td>
<td style="width: 25.3505%; height: 52.7969px;">Professor</td>
<td style="width: 23.6119%; height: 52.7969px;">aniltripathi</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/anoop">Anoop Ambili</a></td>
<td align="left">EES</td>
<td align="left">Associate Professor</td>
<td align="left">anoop</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/anusabhlok">Anu Sabhlok</a></td>
<td align="left">HSS</td>
<td align="left">Professor</td>
<td align="left">anusablok</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/arghyamondal">Arghya Mondal</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">arghyamondal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/akde">Arijit Kumar De</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">akde</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/arunika">Arunika Mukhopadhaya</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">arunika</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/arvind">Arvind</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">arvind</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/arvindshakya">Arvind Kumar Shakya</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">arvindshakya</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/bsinha">Baerbel Sinha</a></td>
<td align="left">EES</td>
<td align="left">Professor</td>
<td align="left">bsinha</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/balanarayan">Balanarayan Pananghat</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor </td>
<td align="left">balanarayan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/chanchal">Chanchal Kumar</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">chanchal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/aribam">Chandrakant Sharma Aribam</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">aribam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/chandrakanta">Chandrakanta Ojha</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">chandrakanta</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/cbalwe">Chetan Tukaram Balwe</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">cbalwe</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/adhikari">Debashis Adhikari</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">adhikari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/debdulals">Debdulal Saha</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">debdulals</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/chakraborty">Dipanjan Chakraborty</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">chakraborty</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/eswaraiahc">Eswaraiah Chakali</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">eswaraiahc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/goutam">Goutam Sheet</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">goutam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/hkjassal">Harvinder Kaur Jassal</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">hkjassal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/hasan">Hasan Mohammad</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">hasan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/indranil">Indranil Banerjee</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">indranil</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/jasjeet">Jasjeet Singh Bagla</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">jasjeet</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/jgeorge">Jino George</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">jgeorge</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/jogender">Jogender Singh</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">jogender</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/jotsaroop">Jotsaroop Kaur</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">jotsaroop</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/jyotima">Jyotima Kanaujia</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">Jyotima</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/kausik">Kausik Chattopadhyay</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">kausik</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kpsingh">Kamal Priya Singh</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">kpsingh</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/yogendran">K. P. Yogendran</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">yogendran</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/krsham">K. R. Shamasundar</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">krsham</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kavita">Kavita Dorai</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">kavita</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kinjalk">Kinjalk Lochan</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">kinjalk</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/krishnendu">Krishnendu Gongopadhyay</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">krishnendu</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/kritikamgarg">Kritika M. Garg</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">kritikamgarg</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/vigneshkuduvar">Kuduva R. Vignesh</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">vigneshkuduvar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/sandhuks">Kuljeet Sandhu</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">sandhuks</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/lingaraj">Lingaraj Sahu</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">lingaraj</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/lolitika">Lolitika Mandal</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">lolitika</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/msharma">Mahak Sharma</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">msharma</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/mahender">Mahender Singh</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">mahender</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/mnbera">Manabendra Nath Bera</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">mnbera</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/mandip">Mandip Singh</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">mandip</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/manjari">Manjari Jain</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">manjari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/manojkumar">Manoj Kumar</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">manojkumar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/mihirsheth">Mihir Sheth</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">mihirsheth</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/prasad">N G Prasad</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">prasad</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/neeraja">Neeraja Sahasrabudhe</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">neeraja</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/pankaj-kushwaha">Pankaj Kushwaha</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">pankaj.kushwaha</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/parthrc">Parth R. Chauhan</a></td>
<td align="left">HSS</td>
<td align="left">Associate Professor</td>
<td align="left">parthrc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/philosek">Philose Koshy</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">philosek</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/psardar">Pranab Sardar</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">psardar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/prasenjit-das">Prasenjit Das</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">prasenjit.das</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/pritam">Pritam Mondal</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">pritam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/pritikanehra">Pritika</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">pritikanehra</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/cppriyakumari">Priyakumari C P</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">cppriyakumari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/guptasarma">Purnananda Guptasarma</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">guptasarma</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/rramesh">Ramesh Ramachandran</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">rramesh</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/rvijayan">R. Vijaya Anand</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">rvijayan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/rachnachaba">Rachna Chaba</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">rachnachaba</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/raj">Raj Kumar Roy</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">raj</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/rkapri">Rajeev Kapri</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">rkapri</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/rajeshra">Rajesh Ramachandran</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">rajeshra</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/rajuattada">Raju Attada</a></td>
<td align="left">EES</td>
<td align="left">Associate Professor</td>
<td align="left">rajuattada</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/ryadav">Ram Yadav</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">ryadav</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/rsjohal">Ramandeep Singh Johal</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">rsjohal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/ravidevani">Ravi Sureshbhai Devani</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">ravidevani</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/rhitoban">Rhitoban Ray Choudhury</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">rhitoban</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/ritajyoti">Ritajyoti Bandyopadhyay</a></td>
<td align="left">HSS</td>
<td align="left">Associate Professor</td>
<td align="left">ritajyoti</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/ramsastry">S. S. V. Rama Sastry</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">ramsastry</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/sababu">S. Arulananda babu</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">sababu</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/srakshit">Sabyasachi Rakshit</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">srakshit</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/sadhancdas">Sadhan Chandra Das</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">sadhancdas</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/samarjit">Samarjit Bhattacharyya</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">samarjit</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/skbiswas">Samir Kumar Biswas</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">skbiswas</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/samrat">Samrat Ghosh</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">samrat</td>
</tr>
<tr>

Let us scrape one of the sections

In [71]:
faculty_section = soup.find("section" , id = "Faculty")
print(faculty_section)

<section class="sppb-section" id="Faculty"><div class="sppb-row-container"><div class="sppb-section-title center"><h3 class="sppb-title-heading">FACULTY MEMBERS</h3></div><div class="sppb-row"><div class="sppb-row-column" id="column-wrap-id-O34SxlZCxdrZbIGOpAgX1"><div class="sppb-column" id="column-id-O34SxlZCxdrZbIGOpAgX1"><div class="sppb-column-addons"><div class="sppb-addon-wrapper addon-root-text-block" id="sppb-addon-wrapper-1722846349938"><div class="clearfix" id="sppb-addon-1722846349938"><div class="sppb-addon sppb-addon-text-block"><div class="sppb-addon-content"><table border="0" style="border-collapse: collapse; height: 58px;">
<tbody>
<tr>
<td style="width: 10%;"><img height="50" src="/images/siteimages/logo/icons/searchicon.gif" width="50"/></td>
<td><span style="font-size: 18px;"><a href="/people/faculty-search"><span style="text-decoration: underline;"><strong>FACULTY</strong> <strong>DIRECTORY SEARCH</strong></span></a></span></td>
</tr>
</tbody>
</table>
<p>mailto: Email@iisermohali.ac.in</p></div></div></div></div><div class="sppb-addon-wrapper addon-root-tab" id="sppb-addon-wrapper-j8krzhWp9jPukn9ZeI6_b"><div class="clearfix" id="sppb-addon-j8krzhWp9jPukn9ZeI6_b"><div class="sppb-addon sppb-addon-tab"><div class="sppb-addon-content sppb-tab sppb-custom-tab sppb-tab-nav-position"><ul class="sppb-nav sppb-nav-custom" role="tablist"><li class="active" role="presentation"><a aria-controls="sppb-tab-j8krzhWp9jPukn9ZeI6_b0" aria-selected="true" class="" data-toggle="sppb-tab" href="#sppb-tab-j8krzhWp9jPukn9ZeI6_b0" id="sppb-content-j8krzhWp9jPukn9ZeI6_b0" role="tab"> Regular Faculty </a></li><li class="" role="presentation"><a aria-controls="sppb-tab-j8krzhWp9jPukn9ZeI6_b1" aria-selected="false" class="" data-toggle="sppb-tab" href="#sppb-tab-j8krzhWp9jPukn9ZeI6_b1" id="sppb-content-j8krzhWp9jPukn9ZeI6_b1" role="tab"> Inspire Faculty </a></li><li class="" role="presentation"><a aria-controls="sppb-tab-j8krzhWp9jPukn9ZeI6_b2" aria-selected="false" class="" data-toggle="sppb-tab" href="#sppb-tab-j8krzhWp9jPukn9ZeI6_b2" id="sppb-content-j8krzhWp9jPukn9ZeI6_b2" role="tab"> Lecturers </a></li><li class="" role="presentation"><a aria-controls="sppb-tab-j8krzhWp9jPukn9ZeI6_b3" aria-selected="false" class="" data-toggle="sppb-tab" href="#sppb-tab-j8krzhWp9jPukn9ZeI6_b3" id="sppb-content-j8krzhWp9jPukn9ZeI6_b3" role="tab"> Visiting Faculty </a></li><li class="" role="presentation"><a aria-controls="sppb-tab-j8krzhWp9jPukn9ZeI6_b4" aria-selected="false" class="" data-toggle="sppb-tab" href="#sppb-tab-j8krzhWp9jPukn9ZeI6_b4" id="sppb-content-j8krzhWp9jPukn9ZeI6_b4" role="tab"> Adjunct Faculty </a></li><li class="" role="presentation"><a aria-controls="sppb-tab-j8krzhWp9jPukn9ZeI6_b5" aria-selected="false" class="" data-toggle="sppb-tab" href="#sppb-tab-j8krzhWp9jPukn9ZeI6_b5" id="sppb-content-j8krzhWp9jPukn9ZeI6_b5" role="tab"> Former Faculty  </a></li><li class="" role="presentation"><a aria-controls="sppb-tab-j8krzhWp9jPukn9ZeI6_b6" aria-selected="false" class="" data-toggle="sppb-tab" href="#sppb-tab-j8krzhWp9jPukn9ZeI6_b6" id="sppb-content-j8krzhWp9jPukn9ZeI6_b6" role="tab"> Honorary Professors </a></li><li class="" role="presentation"><a aria-controls="sppb-tab-j8krzhWp9jPukn9ZeI6_b7" aria-selected="false" class="" data-toggle="sppb-tab" href="#sppb-tab-j8krzhWp9jPukn9ZeI6_b7" id="sppb-content-j8krzhWp9jPukn9ZeI6_b7" role="tab"> Emeritus Professors </a></li></ul><div class="sppb-tab-content sppb-tab-custom-content"><div aria-labelledby="sppb-content-j8krzhWp9jPukn9ZeI6_b0" class="sppb-tab-pane sppb-fade active in" id="sppb-tab-j8krzhWp9jPukn9ZeI6_b0" role="tabpanel"><div class="sppb-section" id="section-id-45GdjXWlwmJDlBdZeJ1nK"><div class="sppb-container-inner"><div class="sppb-row sppb-nested-row"><div class="sppb-row-column" id="column-wrap-id-1727418862643"><div class="sppb-column" id="column-id-1727418862643"><div class="sppb-column-addons"><div class="sppb-addon-wrapper addon-root-raw-html" id="sppb-addon-wrapper-1727418893050"><div class="clearfix" id="sppb-addon-1727418893050"><div class="sppb-addon sppb-addon-raw-html"><div class="sppb-addon-content"><!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>Table Filter with Consistent Row Height</title>
<style>

table.factable {
    border-collapse: collapse !important;
    width: 100% !important;
    height: auto !important;
    overflow: hidden !important;
    border: solid 1px #CCC !important;
    text-align: left !important;
    border-radius: 5px !important;
}

/* Style for the header row */
table.factable thead tr {
    background-color: #006769 !important;
    color: #ffffff !important;
}

/* Default row styles */
table.factable tbody tr:nth-child(even) {
    background-color: #ffffff !important;
}

table.factable tbody tr:nth-child(odd) {
    background-color: #dddddd !important;
}

table.factable td, table.factable th {
    padding: 8px !important;
    border: 1px solid #ddd !important;
}

/* Hide rows without disturbing layout */
       table.factable tbody tr.hidden {
            display: none; /* Completely hide the row */
        }
    </style>
</head>
<body>
<label for="deptFilter">Filter by Department:</label>
<select id="deptFilter" onchange="filterTable()">
<option value="">All</option>
<option value="DMS">Department of Mathematical Sciences (DMS)</option>
<option value="DPS">Department of Physical Sciences (DPS)</option>
<option value="DCS">Department of Chemical Sciences (DCS)</option>
<option value="DBS">Department of Biological Sciences (DBS)</option>
<option value="EES">Department of Earth &amp; Environmental Sciences (EES)</option>
<option value="HSS">Department of Humanities &amp; Social Sciences (HSS)</option>
</select>
<br \=""/>
<div class="table-responsive">
<table class="factable" id="facultytable" style="border-collapse: collapse; width: 100%;">
<thead>
<tr>
<th align="left">Name</th>
<th align="left">Department</th>
<th align="left">Designation</th>
<th align="left">Email</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left"><a href="/faculty/dms/aganguli">Abhik Ganguli</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">aganguli</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/abhishek">Abhishek Chaudhuri</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">abhishek</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/adrene">Adrene Freeda Dcruz</a></td>
<td align="left">HSS</td>
<td align="left">Associate Professor</td>
<td align="left">adrene</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/maharana">Alok Maharana</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">maharana</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/ashivaji">Ambresh Shivaji</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">ashivaji</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/amardeep">Amar Deep</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">amardeep</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/amitk">Amit Kulshrestha</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">amitk</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/ananthv">Ananth Venkatesan</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">ananthv</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/angshurc">Angshuman Roy Choudhury</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">angshurc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/adasanna">Anil Kumar Dasanna</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">adasanna</td>
</tr>
<tr>
<td style="width: 31.5199%; height: 52.7969px;"><a href="/faculty/dbs/aniltripathi">Anil Kumar Tripathi</a></td>
<td style="width: 19.5177%; height: 52.7969px;">DBS</td>
<td style="width: 25.3505%; height: 52.7969px;">Professor</td>
<td style="width: 23.6119%; height: 52.7969px;">aniltripathi</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/anoop">Anoop Ambili</a></td>
<td align="left">EES</td>
<td align="left">Associate Professor</td>
<td align="left">anoop</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/anusabhlok">Anu Sabhlok</a></td>
<td align="left">HSS</td>
<td align="left">Professor</td>
<td align="left">anusablok</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/arghyamondal">Arghya Mondal</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">arghyamondal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/akde">Arijit Kumar De</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">akde</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/arunika">Arunika Mukhopadhaya</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">arunika</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/arvind">Arvind</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">arvind</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/arvindshakya">Arvind Kumar Shakya</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">arvindshakya</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/bsinha">Baerbel Sinha</a></td>
<td align="left">EES</td>
<td align="left">Professor</td>
<td align="left">bsinha</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/balanarayan">Balanarayan Pananghat</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor </td>
<td align="left">balanarayan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/chanchal">Chanchal Kumar</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">chanchal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/aribam">Chandrakant Sharma Aribam</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">aribam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/chandrakanta">Chandrakanta Ojha</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">chandrakanta</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/cbalwe">Chetan Tukaram Balwe</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">cbalwe</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/adhikari">Debashis Adhikari</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">adhikari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/debdulals">Debdulal Saha</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">debdulals</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/chakraborty">Dipanjan Chakraborty</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">chakraborty</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/eswaraiahc">Eswaraiah Chakali</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">eswaraiahc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/goutam">Goutam Sheet</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">goutam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/hkjassal">Harvinder Kaur Jassal</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">hkjassal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/hasan">Hasan Mohammad</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">hasan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/indranil">Indranil Banerjee</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">indranil</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/jasjeet">Jasjeet Singh Bagla</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">jasjeet</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/jgeorge">Jino George</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">jgeorge</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/jogender">Jogender Singh</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">jogender</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/jotsaroop">Jotsaroop Kaur</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">jotsaroop</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/jyotima">Jyotima Kanaujia</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">Jyotima</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/kausik">Kausik Chattopadhyay</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">kausik</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kpsingh">Kamal Priya Singh</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">kpsingh</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/yogendran">K. P. Yogendran</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">yogendran</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/krsham">K. R. Shamasundar</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">krsham</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kavita">Kavita Dorai</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">kavita</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kinjalk">Kinjalk Lochan</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">kinjalk</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/krishnendu">Krishnendu Gongopadhyay</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">krishnendu</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/kritikamgarg">Kritika M. Garg</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">kritikamgarg</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/vigneshkuduvar">Kuduva R. Vignesh</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">vigneshkuduvar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/sandhuks">Kuljeet Sandhu</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">sandhuks</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/lingaraj">Lingaraj Sahu</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">lingaraj</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/lolitika">Lolitika Mandal</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">lolitika</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/msharma">Mahak Sharma</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">msharma</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/mahender">Mahender Singh</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">mahender</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/mnbera">Manabendra Nath Bera</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">mnbera</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/mandip">Mandip Singh</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">mandip</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/manjari">Manjari Jain</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">manjari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/manojkumar">Manoj Kumar</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">manojkumar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/mihirsheth">Mihir Sheth</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">mihirsheth</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/prasad">N G Prasad</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">prasad</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/neeraja">Neeraja Sahasrabudhe</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">neeraja</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/pankaj-kushwaha">Pankaj Kushwaha</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">pankaj.kushwaha</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/parthrc">Parth R. Chauhan</a></td>
<td align="left">HSS</td>
<td align="left">Associate Professor</td>
<td align="left">parthrc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/philosek">Philose Koshy</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">philosek</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/psardar">Pranab Sardar</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">psardar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/prasenjit-das">Prasenjit Das</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">prasenjit.das</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/pritam">Pritam Mondal</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">pritam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/pritikanehra">Pritika</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">pritikanehra</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/cppriyakumari">Priyakumari C P</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">cppriyakumari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/guptasarma">Purnananda Guptasarma</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">guptasarma</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/rramesh">Ramesh Ramachandran</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">rramesh</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/rvijayan">R. Vijaya Anand</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">rvijayan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/rachnachaba">Rachna Chaba</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">rachnachaba</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/raj">Raj Kumar Roy</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">raj</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/rkapri">Rajeev Kapri</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">rkapri</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/rajeshra">Rajesh Ramachandran</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">rajeshra</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/rajuattada">Raju Attada</a></td>
<td align="left">EES</td>
<td align="left">Associate Professor</td>
<td align="left">rajuattada</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/ryadav">Ram Yadav</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">ryadav</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/rsjohal">Ramandeep Singh Johal</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">rsjohal</td>
</tr>
<tr>

In [72]:
#get table containing faculty names
faculty_table = soup.find("table", id= "facultytable")
print(faculty_table)
rows  = faculty_table.find("tbody").find_all("tr")
print(len(rows))
facultydata = []
for row in rows:
    name = row.find_all("td")[0].get_text(strip=True)
    department = row.find_all("td")[1].get_text(strip=True)
    designation =  row.find_all("td")[2].get_text(strip=True)
    emailusername = row.find_all("td")[3].get_text(strip=True)
    plink = row.find_all("td")[0].find("a")["href"]
    facultydata.append({"Name" : name, "Department" : department, "Designation" : designation, "Email" : emailusername, "Profile Link" : plink})

<table class="factable" id="facultytable" style="border-collapse: collapse; width: 100%;">
<thead>
<tr>
<th align="left">Name</th>
<th align="left">Department</th>
<th align="left">Designation</th>
<th align="left">Email</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left"><a href="/faculty/dms/aganguli">Abhik Ganguli</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">aganguli</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/abhishek">Abhishek Chaudhuri</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">abhishek</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/adrene">Adrene Freeda Dcruz</a></td>
<td align="left">HSS</td>
<td align="left">Associate Professor</td>
<td align="left">adrene</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/maharana">Alok Maharana</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">maharana</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/ashivaji">Ambresh Shivaji</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">ashivaji</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/amardeep">Amar Deep</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">amardeep</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/amitk">Amit Kulshrestha</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">amitk</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/ananthv">Ananth Venkatesan</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">ananthv</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/angshurc">Angshuman Roy Choudhury</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">angshurc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/adasanna">Anil Kumar Dasanna</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">adasanna</td>
</tr>
<tr>
<td style="width: 31.5199%; height: 52.7969px;"><a href="/faculty/dbs/aniltripathi">Anil Kumar Tripathi</a></td>
<td style="width: 19.5177%; height: 52.7969px;">DBS</td>
<td style="width: 25.3505%; height: 52.7969px;">Professor</td>
<td style="width: 23.6119%; height: 52.7969px;">aniltripathi</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/anoop">Anoop Ambili</a></td>
<td align="left">EES</td>
<td align="left">Associate Professor</td>
<td align="left">anoop</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/anusabhlok">Anu Sabhlok</a></td>
<td align="left">HSS</td>
<td align="left">Professor</td>
<td align="left">anusablok</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/arghyamondal">Arghya Mondal</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">arghyamondal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/akde">Arijit Kumar De</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">akde</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/arunika">Arunika Mukhopadhaya</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">arunika</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/arvind">Arvind</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">arvind</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/arvindshakya">Arvind Kumar Shakya</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">arvindshakya</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/bsinha">Baerbel Sinha</a></td>
<td align="left">EES</td>
<td align="left">Professor</td>
<td align="left">bsinha</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/balanarayan">Balanarayan Pananghat</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor </td>
<td align="left">balanarayan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/chanchal">Chanchal Kumar</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">chanchal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/aribam">Chandrakant Sharma Aribam</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">aribam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/chandrakanta">Chandrakanta Ojha</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">chandrakanta</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/cbalwe">Chetan Tukaram Balwe</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">cbalwe</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/adhikari">Debashis Adhikari</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">adhikari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/debdulals">Debdulal Saha</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">debdulals</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/chakraborty">Dipanjan Chakraborty</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">chakraborty</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/eswaraiahc">Eswaraiah Chakali</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">eswaraiahc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/goutam">Goutam Sheet</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">goutam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/hkjassal">Harvinder Kaur Jassal</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">hkjassal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/hasan">Hasan Mohammad</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">hasan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/indranil">Indranil Banerjee</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">indranil</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/jasjeet">Jasjeet Singh Bagla</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">jasjeet</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/jgeorge">Jino George</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">jgeorge</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/jogender">Jogender Singh</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">jogender</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/jotsaroop">Jotsaroop Kaur</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">jotsaroop</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/jyotima">Jyotima Kanaujia</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">Jyotima</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/kausik">Kausik Chattopadhyay</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">kausik</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kpsingh">Kamal Priya Singh</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">kpsingh</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/yogendran">K. P. Yogendran</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">yogendran</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/krsham">K. R. Shamasundar</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">krsham</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kavita">Kavita Dorai</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">kavita</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/kinjalk">Kinjalk Lochan</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">kinjalk</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/krishnendu">Krishnendu Gongopadhyay</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">krishnendu</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/kritikamgarg">Kritika M. Garg</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">kritikamgarg</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/vigneshkuduvar">Kuduva R. Vignesh</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">vigneshkuduvar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/sandhuks">Kuljeet Sandhu</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">sandhuks</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/lingaraj">Lingaraj Sahu</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">lingaraj</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/lolitika">Lolitika Mandal</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">lolitika</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/msharma">Mahak Sharma</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">msharma</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/mahender">Mahender Singh</a></td>
<td align="left">DMS</td>
<td align="left">Professor</td>
<td align="left">mahender</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/mnbera">Manabendra Nath Bera</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">mnbera</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/mandip">Mandip Singh</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">mandip</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/manjari">Manjari Jain</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">manjari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/manojkumar">Manoj Kumar</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">manojkumar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/mihirsheth">Mihir Sheth</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">mihirsheth</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/prasad">N G Prasad</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">prasad</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/neeraja">Neeraja Sahasrabudhe</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">neeraja</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/pankaj-kushwaha">Pankaj Kushwaha</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">pankaj.kushwaha</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/parthrc">Parth R. Chauhan</a></td>
<td align="left">HSS</td>
<td align="left">Associate Professor</td>
<td align="left">parthrc</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/philosek">Philose Koshy</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">philosek</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/psardar">Pranab Sardar</a></td>
<td align="left">DMS</td>
<td align="left">Associate Professor</td>
<td align="left">psardar</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/prasenjit-das">Prasenjit Das</a></td>
<td align="left">DPS</td>
<td align="left">Assistant Professor</td>
<td align="left">prasenjit.das</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/pritam">Pritam Mondal</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">pritam</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/pritikanehra">Pritika</a></td>
<td align="left">HSS</td>
<td align="left">Assistant Professor</td>
<td align="left">pritikanehra</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/cppriyakumari">Priyakumari C P</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">cppriyakumari</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/guptasarma">Purnananda Guptasarma</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">guptasarma</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/rramesh">Ramesh Ramachandran</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">rramesh</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/rvijayan">R. Vijaya Anand</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">rvijayan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/rachnachaba">Rachna Chaba</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">rachnachaba</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/raj">Raj Kumar Roy</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">raj</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/rkapri">Rajeev Kapri</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">rkapri</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/rajeshra">Rajesh Ramachandran</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">rajeshra</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/rajuattada">Raju Attada</a></td>
<td align="left">EES</td>
<td align="left">Associate Professor</td>
<td align="left">rajuattada</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/ryadav">Ram Yadav</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">ryadav</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/rsjohal">Ramandeep Singh Johal</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">rsjohal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/ravidevani">Ravi Sureshbhai Devani</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">ravidevani</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/rhitoban">Rhitoban Ray Choudhury</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">rhitoban</td>
</tr>
<tr>
<td align="left"><a href="/faculty/hss/ritajyoti">Ritajyoti Bandyopadhyay</a></td>
<td align="left">HSS</td>
<td align="left">Associate Professor</td>
<td align="left">ritajyoti</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/ramsastry">S. S. V. Rama Sastry</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">ramsastry</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/sababu">S. Arulananda babu</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">sababu</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/srakshit">Sabyasachi Rakshit</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">srakshit</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/sadhancdas">Sadhan Chandra Das</a></td>
<td align="left">DBS</td>
<td align="left">Assistant Professor</td>
<td align="left">sadhancdas</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/samarjit">Samarjit Bhattacharyya</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">samarjit</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/skbiswas">Samir Kumar Biswas</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">skbiswas</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/samrat">Samrat Ghosh</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">samrat</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/mukhopadhyay">Samrat Mukhopadhyay</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">mukhopadhyay</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/sajal">Sajal Kumar Giri</a></td>
<td align="left">DCS</td>
<td align="left">Assistant Professor</td>
<td align="left">sajal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/sanjaymandal">Sanjay Mandal</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">sanjaymandal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/sanchita">Sanchita Sengupta</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">sanchita</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/skgoyal">Sandeep K. Goyal</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">skgoyal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/sanjaysingh">Sanjay Singh</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">sanjaysingh</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/sanjeev">Sanjeev Kumar</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">sanjeev</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/skpal">Santanu Kumar Pal</a></td>
<td align="left">DCS</td>
<td align="left">Professor</td>
<td align="left">skpal</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/santhoshkp">Santhosh Kumar Pamula</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">santhoshkp</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/ssatbhai">Santosh B. Satbhai</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">ssatbhai</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/sjena">Satyajit Jena</a></td>
<td align="left">DPS</td>
<td align="left">Associate Professor</td>
<td align="left">sjena</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/shane">Shane D'Mello</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">shane</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/sbhattacharya">Sharmila Bhattacharya</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">sbhattacharya</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/sharvan">Sharvan Sehrawat</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">sharvan</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/shashibp">Shashi Bhushan Pandit</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">shashibp</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/skmishra">Shravan Kumar Mishra</a></td>
<td align="left">DBS</td>
<td align="left">Associate Professor</td>
<td align="left">skmishra</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dms/somamaity">Soma Maity</a></td>
<td align="left">DMS</td>
<td align="left">Assistant Professor</td>
<td align="left">somamaity</td>
</tr>
<tr>
<td align="left"><a href="/faculty/ees/sourabh">Sourabh Bhattacharya</a></td>
<td align="left">EES</td>
<td align="left">Assistant Professor</td>
<td align="left">sourabh</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/smaiti">Subhabrata Maiti</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">smaiti</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dps/sudeshna">Sudeshna Sinha</a></td>
<td align="left">DPS</td>
<td align="left">Professor</td>
<td align="left">sudeshna</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dbs/sudip">Sudip Mandal</a></td>
<td align="left">DBS</td>
<td align="left">Professor</td>
<td align="left">sudip</td>
</tr>
<tr>
<td align="left"><a href="/faculty/dcs/sugumarv">Sugumar Venkataramani</a></td>
<td align="left">DCS</td>
<td align="left">Associate Professor</td>
<td align="left">sugumarv</td>

In [73]:
df = pd.DataFrame(facultydata)
df.head()

,Name,Department,Designation,Email,Profile Link
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,/faculty/dms/aganguli
1,Abhishek Chaudhuri,DPS,Professor,abhishek,/faculty/dps/abhishek
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,/faculty/hss/adrene
3,Alok Maharana,DMS,Assistant Professor,maharana,/faculty/dms/maharana
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,/faculty/dps/ashivaji

A few checks

In [74]:
tabs= soup.find_all("div", class_ = "sppb-tab-pane")
print(len(tabs))

12

In [75]:
tab_names = soup.select("ul.sppb-nav-custom li a")
for tab in tab_names:
    print(tab.get_text(strip= True))

Regular Faculty
Inspire Faculty
Lecturers
Visiting Faculty
Adjunct Faculty
Former Faculty
Honorary Professors
Emeritus Professors
Administrative Staff
Technical Staff
Institute Fellows
Project Scientists

In [76]:
for i, tab in enumerate(tabs):
    print(i, len(tab.find_all("table")))

0 1
1 1
2 1
3 1
4 1
5 2
6 2
7 1
8 1
9 1
10 1
11 1

In [77]:
for i, tab in enumerate(tabs):
    print(i, tab.find("h2").get_text(strip=True) if tab.find("h2") else "NO H2")

0 NO H2
1 Inspire Faculty
2 Lecturers
3 Visiting Faculty
4 Adjunct Faculty
5 Former Faculty - Regular
6 Honorary Professors
7 Emeritus Professors
8 Administrative Staff
9 Technical Staff
10 Institute Fellows
11 Project Scientists

In [78]:
regular = tabs[0]

tables = regular.find_all("table")

print(len(tables))

for i, table in enumerate(tables):
    print("\nTABLE", i)
    print(table.get_text(" ", strip=True)[:500])

1

TABLE 0
Name Department Designation Email Abhik Ganguli DMS Assistant Professor aganguli Abhishek Chaudhuri DPS Professor abhishek Adrene Freeda Dcruz HSS Associate Professor adrene Alok Maharana DMS Assistant Professor maharana Ambresh Shivaji DPS Associate Professor ashivaji Amar Deep DBS Assistant Professor amardeep Amit Kulshrestha DMS Professor amitk Ananth Venkatesan DPS Associate Professor ananthv Angshuman Roy Choudhury DCS Assistant Professor angshurc Anil Kumar Dasanna DPS Assistant Professor

In [79]:
#get table containing faculty names
faculty_table = soup.find("table", id= "facultytable")
rows  = faculty_table.find("tbody").find_all("tr")
print(len(rows))
facultydata = []
for row in rows:
    name = row.find_all("td")[0].get_text(strip=True)
    department = row.find_all("td")[1].get_text(strip=True)
    designation =  row.find_all("td")[2].get_text(strip=True)
    emailusername = row.find_all("td")[3].get_text(strip=True)
    plink = row.find_all("td")[0].find("a")["href"]
    facultydata.append({"Name" : name, "Department" : department, "Designation" : designation, "Email" : emailusername, "Profile Link" : plink})
df = pd.DataFrame(facultydata)
df.head()

122

,Name,Department,Designation,Email,Profile Link
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,/faculty/dms/aganguli
1,Abhishek Chaudhuri,DPS,Professor,abhishek,/faculty/dps/abhishek
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,/faculty/hss/adrene
3,Alok Maharana,DMS,Assistant Professor,maharana,/faculty/dms/maharana
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,/faculty/dps/ashivaji

In [80]:
for name, tab in zip(tab_names, tabs):
     category = name.get_text(strip=True)
     tables = tab.find_all("table")
     print(category, len(tables))
     for table in tables:
        rows = table.find_all("tr")[1:]
        for row in rows:
            cells = row.find_all("td")
            print(len(cells))

Regular Faculty 1
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
Inspire Faculty 1
Lecturers 1
4
4
Visiting Faculty 1
4
4
4
Adjunct Faculty 1
4
Former Faculty 2
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
Honorary Professors 2
4
4
4
5
5
Emeritus Professors 1
4
4
Administrative Staff 1
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
Technical Staff 1
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
Institute Fellows 1
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
Project Scientists 1
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3

In [81]:
for category_link, tab in zip(tab_names, tabs):

    category = category_link.get_text(strip=True)

    print("\nCATEGORY:", category)

    for i, table in enumerate(tab.find_all("table")):

        print("TABLE:", i)

        first_row = table.find("tr")

        headers = first_row.find_all(["th", "td"])

        for header in headers:
            print(header.get_text(" ", strip=True))

CATEGORY: Regular Faculty
TABLE: 0
Name
Department
Designation
Email

CATEGORY: Inspire Faculty
TABLE: 0
S.No.
Name
Department
Email

CATEGORY: Lecturers
TABLE: 0
S.No.
Name
Department
Email

CATEGORY: Visiting Faculty
TABLE: 0
S.No.
Name
Department
Email

CATEGORY: Adjunct Faculty
TABLE: 0
S.No.
Name
Department
Email

CATEGORY: Former Faculty
TABLE: 0
S.No.
Name
Department
Designation
TABLE: 1
S.No.
Name
Department
Designation

CATEGORY: Honorary Professors
TABLE: 0
S.No.
Name
Department
Email
TABLE: 1
S.No.
Name
Department
Designation
Email

CATEGORY: Emeritus Professors
TABLE: 0
S.No.
Name
Department
Email

CATEGORY: Administrative Staff
TABLE: 0
Name
Designation
Office/Section
Email

CATEGORY: Technical Staff
TABLE: 0
Name
Designation
Office/Section
Email

CATEGORY: Institute Fellows
TABLE: 0
Name
PI
Department

CATEGORY: Project Scientists
TABLE: 0
Name
Project No.
Department

In [82]:
for category_link, tab in zip(tab_names, tabs):

    category = category_link.get_text(strip=True)

    print("\nCATEGORY:", category)

    for i, table in enumerate(tab.find_all("table")):

        first_row = table.find("tr")

        headers = first_row.find_all(["th", "td"])

        print("TABLE:", i)
        print([header.get_text(" ", strip=True) for header in headers])

CATEGORY: Regular Faculty
TABLE: 0
['Name', 'Department', 'Designation', 'Email']

CATEGORY: Inspire Faculty
TABLE: 0
['S.No.', 'Name', 'Department', 'Email']

CATEGORY: Lecturers
TABLE: 0
['S.No.', 'Name', 'Department', 'Email']

CATEGORY: Visiting Faculty
TABLE: 0
['S.No.', 'Name', 'Department', 'Email']

CATEGORY: Adjunct Faculty
TABLE: 0
['S.No.', 'Name', 'Department', 'Email']

CATEGORY: Former Faculty
TABLE: 0
['S.No.', 'Name', 'Department', 'Designation']
TABLE: 1
['S.No.', 'Name', 'Department', 'Designation']

CATEGORY: Honorary Professors
TABLE: 0
['S.No.', 'Name', 'Department', 'Email']
TABLE: 1
['S.No.', 'Name', 'Department', 'Designation', 'Email']

CATEGORY: Emeritus Professors
TABLE: 0
['S.No.', 'Name', 'Department', 'Email']

CATEGORY: Administrative Staff
TABLE: 0
['Name', 'Designation', 'Office/Section', 'Email']

CATEGORY: Technical Staff
TABLE: 0
['Name', 'Designation', 'Office/Section', 'Email']

CATEGORY: Institute Fellows
TABLE: 0
['Name', 'PI', 'Department']

CATEGORY: Project Scientists
TABLE: 0
['Name', 'Project No.', 'Department']

Lets scrape the data

In [83]:
faculty_data = []

for category_link , tab in zip(tab_names, tabs):
    category = category_link.get_text(strip=True)

    for table in tab.find_all("table"):
        header_row = table.find("tr")
        headers = [
            cell.get_text(" ",strip=True)
            for cell in header_row.find_all(["th", "td"])
        ]
        name_index = headers.index("Name") if "Name" in headers else None
        department_index = headers.index("Department") if "Department" in headers else None
        designation_index = headers.index("Designation") if "Designation" in headers else None
        email_index = headers.index("Email") if "Email" in headers else None

        #Data rows
        for row in table.find_all("tr")[1:]:
         cells = row.find_all("td")
        if not cells or name_index is None:
            continue
        name = cells[name_index].get_text(" ", strip=True)
        department = (
                cells[department_index].get_text(" ", strip=True)
                if department_index is not None
                else None
            )

        designation = (
                cells[designation_index].get_text(" ", strip=True)
                if designation_index is not None
                else None
            )

        email = (
                cells[email_index].get_text(" ", strip=True)
                if email_index is not None
                else None
            )
        link = cells[name_index].find("a")

        profile_link = link.get("href") if link else None
        facultydata.append({
                "Category": category,
                "Name": name,
                "Department": department,
                "Designation": designation,
                "Email": email,
                "Profile Link": profile_link
            })

df = pd.DataFrame(facultydata)

df.head()

,Name,Department,Designation,Email,Profile Link,Category
0,Abhik Ganguli,DMS,Assistant Professor,aganguli,/faculty/dms/aganguli,NaN
1,Abhishek Chaudhuri,DPS,Professor,abhishek,/faculty/dps/abhishek,NaN
2,Adrene Freeda Dcruz,HSS,Associate Professor,adrene,/faculty/hss/adrene,NaN
3,Alok Maharana,DMS,Assistant Professor,maharana,/faculty/dms/maharana,NaN
4,Ambresh Shivaji,DPS,Associate Professor,ashivaji,/faculty/dps/ashivaji,NaN

In [84]:
import os
df.to_csv("iisermohali_faculty.csv", index=False)
print("Saved!")
os.path.exists("iisermohali_faculty.csv")
print(os.path.abspath("iisermohali_faculty.csv"))

Saved!
e:\SEM 5\IDC409\iisermohali_faculty.csv

Let us find faculty information

In [85]:
from urllib.parse import urljoin

base_url = "https://www.iisermohali.ac.in"

def fix_profile_link(x):

    if pd.isna(x):
        return None

    x = str(x)

    # Find the actual IISER faculty path
    if "/faculty/" in x:
        x = x[x.find("/faculty/"):]

    return urljoin(base_url, x)


df["Profile Link"] = df["Profile Link"].apply(fix_profile_link)

In [86]:
print(df["Profile Link"].iloc[0])
print(df["Profile Link"].iloc[1])

https://www.iisermohali.ac.in/faculty/dms/aganguli
https://www.iisermohali.ac.in/faculty/dps/abhishek

In [87]:
profile_url = df["Profile Link"].iloc[0]

response = requests.get(profile_url)

print(profile_url)
print(response.status_code)

https://www.iisermohali.ac.in/faculty/dms/aganguli
200

In [88]:
profile_sections = []
for i, row in df.iterrows():
    name= row["Name"]
    profile_url=row["Profile Link"]
    if pd.isna(profile_url):
        continue
    response = requests.get(profile_url)
    profile_soup= BeautifulSoup(response.text,"html.parser")

    headings = profile_soup.find_all(["h1","h2","h3"])
    heading_text = [
        h.get_text(strip=True)
        for h in headings
        if h.get_text(strip=True)
    ]
    profile_sections.append({"Name": name, "Profile URL": profile_url, "Headings": heading_text})
print("Profiles checked:", len(profile_sections))

KeyboardInterrupt:

In [ ]:
sections_df = pd.DataFrame(profile_sections)

print(sections_df.shape)

(125, 3)

In [ ]:
for _, row in sections_df.iterrows():
    print("\n", row["Name"])
    print(row["Headings"])

 Abhik Ganguli
['IISER MOHALI', 'Dr. Abhik Ganguli', 'Assistant Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Abhishek Chaudhuri
['IISER MOHALI', 'Dr. Abhishek Chaudhuri', 'Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Adrene Freeda Dcruz
['IISER MOHALI', 'Dr. Adrene Freeda Dcruz', 'Associate Professor', 'Department of Humanities and Social Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Alok Maharana
['IISER MOHALI', 'Dr. Alok Maharana', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Ambresh Shivaji
['IISER MOHALI', 'Dr. Ambresh Shivaji', 'Associate Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Amar Deep
['IISER MOHALI', 'Dr. Amar Deep', 'AssistantProfessor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Amit Kulshrestha
['IISER MOHALI', 'Dr. Amit Kulshrestha', 'Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Ananth Venkatesan
['IISER MOHALI', 'Dr. Ananth Venkatesan', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Angshuman Roy Choudhury
['IISER MOHALI', 'Dr. Angshuman Roy Choudhury', 'Assistant Professor', 'Department of Chemical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Anil Kumar Dasanna
['IISER MOHALI', 'Dr. Anil Kumar Dasanna', 'Assistant Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Anil Kumar Tripathi
['IISER MOHALI', 'Dr. Anil Kumar Tripathi', 'Professor', 'Department of Biological Sciences', 'Research Interests', 'Research Interests:', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Anoop Ambili
['IISER MOHALI', 'Dr. Anoop Ambili', 'Associate Professor', 'Department of Earth and Environmental Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Anu Sabhlok
['IISER MOHALI', 'Dr. Anu Sabhlok', 'Professor', 'Department of Humanities and Social Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Arghya Mondal
['IISER MOHALI', 'Dr. Arghya Mondal', 'AssistantProfessor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Arijit Kumar De
['IISER MOHALI', 'Dr. Arijit Kumar De', 'Associate Professor', 'Department of Chemical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Arunika Mukhopadhaya
['IISER MOHALI', 'Dr. Arunika Mukhopadhaya', 'Professor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Arvind
['IISER MOHALI', 'Dr. Arvind', 'Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Arvind Kumar Shakya
['IISER MOHALI', 'Dr. Arvind Kumar Shakya', 'Assistant Professor', 'Department of Earth & Environmental Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Baerbel Sinha
['IISER MOHALI', 'Dr. Baerbel Sinha', 'Professor', 'Department of Earth & Environmental Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Balanarayan Pananghat
['IISER MOHALI', 'Dr. Balanarayan Pananghat', 'Associate Professor', 'Department of Chemical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Chanchal Kumar
['IISER MOHALI', 'Dr. Chanchal Kumar', 'Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Chandrakant Sharma Aribam
['IISER MOHALI', 'Dr. Chandrakant Sharma Aribam', 'Associate Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Chandrakanta Ojha
['IISER MOHALI', 'Dr. Chandrakanta Ojha', 'Assistant Professor', 'Department of Earth and Environmental Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Chetan Tukaram Balwe
['IISER MOHALI', 'Dr. Chetan Tukaram Balwe', 'Associate Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Debashis Adhikari
['IISER MOHALI', 'Dr. Debashis Adhikari', 'Associate Professor', 'Department of Chemical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Debdulal Saha
['IISER MOHALI', 'Dr. Debdulal Saha', 'Assistant Professor', 'Department of Humanities & Social Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Dipanjan Chakraborty
['IISER MOHALI', 'Dr. Dipanjan Chakraborty', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Eswaraiah Chakali
['IISER MOHALI', 'Dr. Eswaraiah Chakali', 'AssistantProfessor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Goutam Sheet
['IISER MOHALI', 'Dr. Goutam Sheet', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Harvinder Kaur Jassal
['IISER MOHALI', 'Dr. Harvinder Kaur Jassal', 'Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Hasan Mohammad
['IISER MOHALI', 'Dr. Hasan Mohammad', 'Assistant Professor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Indranil Banerjee
['IISER MOHALI', 'Dr. Indranil Banerjee', 'Associate Professor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Jasjeet Singh Bagla
['IISER MOHALI', 'Dr. Jasjeet Singh Bagla', 'Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Jino George
['IISER MOHALI', 'Dr. Jino George', 'Associate Professor', 'Department of Chemical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Jogender Singh
['IISER MOHALI', 'Dr. Jogender Singh', 'Assistant Professor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Jotsaroop Kaur
['IISER MOHALI', 'Dr. Jotsaroop Kaur', 'Assistant Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Jyotima Kanaujia
['IISER MOHALI', 'Dr. Jyotima Kanaujia', 'Assistant Professor', 'Department of Earth and Environmental Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Kausik Chattopadhyay
['IISER MOHALI', 'Dr. Kausik Chattopadhyay', 'Professor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Kamal Priya Singh
['IISER MOHALI', 'Dr. Kamal Priya Singh', 'Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 K. P. Yogendran
['IISER MOHALI', 'Dr. K. P. Yogendran', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 K. R. Shamasundar
['IISER MOHALI', 'Dr. Shamasundar K R', 'Assistant Professor', 'Department of Chemical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Kavita Dorai
['IISER MOHALI', 'Dr. Kavita Dorai', 'Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Kinjalk Lochan
['IISER MOHALI', 'Dr. Kinjalk Lochan', 'AssociateProfessor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Krishnendu Gongopadhyay
['IISER MOHALI', 'Dr. Krishnendu Gongopadhyay', 'Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Kritika M. Garg
['IISER MOHALI', 'Dr. Kritika M. Garg', 'AssistantProfessor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Kuduva R. Vignesh
['IISER MOHALI', 'Dr. Kuduva R. Vignesh', 'Assistant Professor', 'Department of Chemical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Kuljeet Sandhu
['IISER MOHALI', 'Dr. Kuljeet Sandhu', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Lingaraj Sahu
['IISER MOHALI', 'Dr. Lingaraj Sahu', 'Associate Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Lolitika Mandal
['IISER MOHALI', 'Dr. Lolitika Mandal', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Mahak Sharma
['IISER MOHALI', 'Dr. Mahak Sharma', 'Professor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Mahender Singh
['IISER MOHALI', 'Dr. Mahender Singh', 'Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Manabendra Nath Bera
['IISER MOHALI', 'Dr. Manabendra Nath Bera', 'Assistant Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Mandip Singh
['IISER MOHALI', 'Dr. Mandip Singh', 'Associate Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Manjari Jain
['IISER MOHALI', 'Dr. Manjari Jain', 'Associate Professor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Manoj Kumar
['IISER MOHALI', 'Dr. Manoj Kumar', 'AssistantProfessor', 'Department of Earth & Environmental Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Mihir Sheth
['IISER MOHALI', 'Dr. Mihir Sheth', 'AssistantProfessor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 N G Prasad
['IISER MOHALI', 'Dr. N G Prasad', 'Professor', 'Department of Biological Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Neeraja Sahasrabudhe
['IISER MOHALI', 'Dr. Neeraja Sahasrabudhe', 'Assistant Professor', 'Department of Mathematical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Pankaj Kushwaha
['IISER MOHALI', 'Dr. Pankaj Kushwaha', 'Assistant Professor', 'Department of Physical Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Parth R. Chauhan
['IISER MOHALI', 'Dr. Parth R. Chauhan', 'Associate Professor', 'Department of Humanities & Social Sciences', 'Research Area', 'Research Interests', 'website policy', 'Connect with us', 'Administrative Sections', 'Campus Facilities', 'Departments', 'committees', 'Archive', 'Links', 'Quick Find', 'Advertisements', 'CAREERS', 'Search']

 Philose Koshy

check for one profile

In [ ]:
def get_section_text(soup, heading_text):

    heading = soup.find(
        lambda tag: tag.name in ["h1", "h2", "h3", "h4"]
        and tag.get_text(" ", strip=True) == heading_text
    )

    if not heading:
        return None

    text = []

    for element in heading.find_all_next():

        if element.name in ["h1", "h2", "h3", "h4"]:
            break

        value = element.get_text(" ", strip=True)

        if value:
            text.append(value)

    return " ".join(text)

In [ ]:
research_area = get_section_text(profile_soup, "Research Area")

research_interests = get_section_text(profile_soup, "Research Interests")

print("AREA:")
print(research_area)

print("\nINTERESTS:")
print(research_interests)

AREA:
Research Area Algebraic Geometry, Algebraic Number Theory, Algebraic Topology

INTERESTS:

Lets find for all

In [ ]:
for headings in sections_df["Headings"]:
    for h in headings:
        print(h)

IISER MOHALI
Dr. Abhik Ganguli
Assistant Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Abhishek Chaudhuri
Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Adrene Freeda Dcruz
Associate Professor
Department of Humanities and Social Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Alok Maharana
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Ambresh Shivaji
Associate Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Amar Deep
AssistantProfessor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Amit Kulshrestha
Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Ananth Venkatesan
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Angshuman Roy Choudhury
Assistant Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Anil Kumar Dasanna
Assistant Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Anil Kumar Tripathi
Professor
Department of Biological Sciences
Research Interests
Research Interests:
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Anoop Ambili
Associate Professor
Department of Earth and Environmental Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Anu Sabhlok
Professor
Department of Humanities and Social Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Arghya Mondal
AssistantProfessor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Arijit Kumar De
Associate Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Arunika Mukhopadhaya
Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Arvind
Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Arvind Kumar Shakya
Assistant Professor
Department of Earth & Environmental Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Baerbel Sinha
Professor
Department of Earth & Environmental Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Balanarayan Pananghat
Associate Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Chanchal Kumar
Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Chandrakant Sharma Aribam
Associate Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Chandrakanta Ojha
Assistant Professor
Department of Earth and Environmental Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Chetan Tukaram Balwe
Associate Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Debashis Adhikari
Associate Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Debdulal Saha
Assistant Professor
Department of Humanities & Social Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Dipanjan Chakraborty
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Eswaraiah Chakali
AssistantProfessor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Goutam Sheet
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Harvinder Kaur Jassal
Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Hasan Mohammad
Assistant Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Indranil Banerjee
Associate Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Jasjeet Singh Bagla
Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Jino George
Associate Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Jogender Singh
Assistant Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Jotsaroop Kaur
Assistant Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Jyotima Kanaujia
Assistant Professor
Department of Earth and Environmental Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Kausik Chattopadhyay
Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Kamal Priya Singh
Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. K. P. Yogendran
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Shamasundar K R
Assistant Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Kavita Dorai
Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Kinjalk Lochan
AssociateProfessor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Krishnendu Gongopadhyay
Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Kritika M. Garg
AssistantProfessor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Kuduva R. Vignesh
Assistant Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Kuljeet Sandhu
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Lingaraj Sahu
Associate Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Lolitika Mandal
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Mahak Sharma
Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Mahender Singh
Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Manabendra Nath Bera
Assistant Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Mandip Singh
Associate Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Manjari Jain
Associate Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Manoj Kumar
AssistantProfessor
Department of Earth & Environmental Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Mihir Sheth
AssistantProfessor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. N G Prasad
Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Neeraja Sahasrabudhe
Assistant Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Pankaj Kushwaha
Assistant Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Parth R. Chauhan
Associate Professor
Department of Humanities & Social Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Philose Koshy
Assistant Professor
Department of Humanities & Social Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Pranab Sardar
Associate Professor
Department of Mathematical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Prasenjit Das
Assistant Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Pritam Mondal
Assistant Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Pritika
Assistant Professor
Department of Humanities & Social Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Priyakumari C P
Assistant Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Purnananda Guptasarma
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Ramesh Ramachandran
Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. R. Vijaya Anand
Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Rachna Chaba
Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Raj Kumar Roy
Associate Professor
Department of Chemical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Rajeev Kapri
Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Rajesh Ramachandran
Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Raju Attada
Associate Professor
Department of Earth & Environmental Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Ram Yadav
Associate Professor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Ramandeep Singh Johal
Professor
Department of Physical Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities
Departments
committees
Archive
Links
Quick Find
Advertisements
CAREERS
Search
IISER MOHALI
Dr. Ravi Suresh Devani
AssistantProfessor
Department of Biological Sciences
Research Area
Research Interests
website policy
Connect with us
Administrative Sections
Campus Facilities

In [ ]:
all_headings = set()

for headings in sections_df["Headings"]:
    all_headings.update(headings)

for h in sorted(all_headings):
    print(h)

Administrative Sections
Advertisements
Archive
Assistant Professor
AssistantProfessor
Associate Professor
AssociateProfessor
CAREERS
Campus Facilities
Connect with us
Department of Biological Sciences
Department of Chemical Sciences
Department of Earth & Environmental Sciences
Department of Earth and Environmental Sciences
Department of Humanities & Social Sciences
Department of Humanities and Social Sciences
Department of Mathematical Sciences
Department of Physical Sciences
Departments
Dr. Abhik Ganguli
Dr. Abhishek Chaudhuri
Dr. Adrene Freeda Dcruz
Dr. Alok Maharana
Dr. Amar Deep
Dr. Ambresh Shivaji
Dr. Amit Kulshrestha
Dr. Ananth Venkatesan
Dr. Angshuman Roy Choudhury
Dr. Anil Kumar Dasanna
Dr. Anil Kumar Tripathi
Dr. Anoop Ambili
Dr. Anu Sabhlok
Dr. Arghya Mondal
Dr. Arijit Kumar De
Dr. Arunika Mukhopadhaya
Dr. Arvind
Dr. Arvind Kumar Shakya
Dr. Baerbel Sinha
Dr. Balanarayan Pananghat
Dr. Chanchal Kumar
Dr. Chandrakant Sharma Aribam
Dr. Chandrakanta Ojha
Dr. Chetan Tukaram Balwe
Dr. Debashis Adhikari
Dr. Debdulal Saha
Dr. Dipanjan Chakraborty
Dr. Eswaraiah Chakali
Dr. Goutam Sheet
Dr. Harvinder Kaur Jassal
Dr. Hasan Mohammad
Dr. Indranil Banerjee
Dr. Jasjeet Singh Bagla
Dr. Jino George
Dr. Jogender Singh
Dr. Jotsaroop Kaur
Dr. Jyotima Kanaujia
Dr. K. P. Yogendran
Dr. Kamal Priya Singh
Dr. Kapil Hari Paranjape
Dr. Kausik Chattopadhyay
Dr. Kavita Dorai
Dr. Kinjalk Lochan
Dr. Krishnendu Gongopadhyay
Dr. Kritika M. Garg
Dr. Kuduva R. Vignesh
Dr. Kuljeet Sandhu
Dr. Lingaraj Sahu
Dr. Lolitika Mandal
Dr. Mahak Sharma
Dr. Mahender Singh
Dr. Manabendra Nath Bera
Dr. Mandip Singh
Dr. Manjari Jain
Dr. Manoj Kumar
Dr. Mihir Sheth
Dr. N G Prasad
Dr. Neeraja Sahasrabudhe
Dr. Pankaj Kushwaha
Dr. Parth R. Chauhan
Dr. Philose Koshy
Dr. Pranab Sardar
Dr. Prasenjit Das
Dr. Pritam Mondal
Dr. Pritika
Dr. Priyakumari C P
Dr. Purnananda Guptasarma
Dr. R. Vijaya Anand
Dr. Rachna Chaba
Dr. Raj Kumar Roy
Dr. Rajeev Kapri
Dr. Rajesh Ramachandran
Dr. Raju Attada
Dr. Ram Yadav
Dr. Ramandeep Singh Johal
Dr. Ramesh Ramachandran
Dr. Ravi Suresh Devani
Dr. Rhitoban Raychoudhury
Dr. Ritajyoti Bandyopadhyay
Dr. S. Arulananda babu
Dr. S. S. V. Rama Sastry
Dr. Sabyasachi Rakshit
Dr. Sadhan Chandra Das
Dr. Sajal Kumar Giri
Dr. Samarjit Bhattacharyya
Dr. Samir Kumar Biswas
Dr. Samrat Ghosh
Dr. Samrat Mukhopadhyay
Dr. Sanchita Sengupta
Dr. Sandeep K. Goyal
Dr. Sanjay Mandal
Dr. Sanjay Singh
Dr. Sanjeev Kumar
Dr. Santanu Kumar Pal
Dr. Santhosh Kumar Pamula
Dr. Santosh B. Satbhai
Dr. Satyajit Jena
Dr. Shamasundar K R
Dr. Shane D'Mello
Dr. Sharmila Bhattacharya
Dr. Sharvan Sehrawat
Dr. Shashi Bhushan Pandit
Dr. Shravan Kumar Mishra
Dr. Soma Maity
Dr. Sourabh Bhattacharya
Dr. Subhabrata Maiti
Dr. Sudesh Kaur Khanduja
Dr. Sudeshna Sinha
Dr. Sudip Mandal
Dr. Sugumar Venkataramani
Dr. Suman Kumar Barman
Dr. Sunil A. Patil
Dr. Tanusree Khandai
Dr. Tripta Bhatia
Dr. Ujjal K. Gautam
Dr. V. Rajesh
Dr. Vaibhav Vaish
Dr. Varadharaj Ravi Srinivasan
Dr. Vidya Devi Negi
Dr. Vinayak Sinha
Dr. Vishal Bhardwaj
Dr. Yashonidhi Pandey
Dr. Yogesh Singh
Dr. Yunus Ali Pulpadan
Honorary Professor
IISER MOHALI
Links
Professor
Quick Find
Research Area
Research Interests
Research Interests:
Search
committees
website policy

In [94]:
def get_tab_text(soup, tab_name):

    tabs = soup.find_all(
        "a",
        attrs={"data-toggle": "sppb-tab"}
    )

    for tab in tabs:

        if tab.get_text(" ", strip=True).rstrip(":") == tab_name:

            target_id = tab.get("href")

            if not target_id:
                return None

            # Remove the # from the href
            target_id = target_id.lstrip("#")

            # Find the content directly by ID
            content = soup.find(id=target_id)

            if content:
                return content.get_text(" ", strip=True)

            return None

    return None

testing for one - all sections

In [98]:
profile_url = df["Profile Link"].iloc[5]

response = requests.get(profile_url)
profile_soup = BeautifulSoup(response.text, "html.parser")

print("CAREER:")
print(get_tab_text(profile_soup, "Career Highlights"))

print("\nAWARDS:")
print(get_tab_text(profile_soup, "Awards & Recognitions"))

print("\nPUBLICATIONS:")
print(get_tab_text(profile_soup, "Publications"))
print("RESEARCH AREA:")
print(get_section_text(profile_soup, "Research Area"))

print("\nRESEARCH INTERESTS:")
print(get_section_text(profile_soup, "Research Interests"))

CAREER:
2020 - 2025 : Postdoctoral Fellow, University of California, San Diego, USA. 2014 - 2019 : Ph.D. (Structural Biology), CSIR-Institute of Microbial Technology, Chandigarh, India. 2011 - 2013 : M.Sc. (Human Genomics), Panjab University, Chandigarh, India. 2008 - 2011 : B.Sc. (Honours) Biotechnology, Himachal Pradesh University, Shimla, India. (College: Himachal Institute of Life Sciences, Paonta Sahib, Himachal Pradesh)

AWARDS:
2020 : Dr. V. C. Vora Best Ph.D. Thesis Award from CSIR-IMTech, Chandigarh. 2016 - 2019 : Senior Research Fellowship, Department of Biotechnology (DBT). Govt. of India. 2014 - 2016 : Junior Research Fellowship, Department of Biotechnology (DBT). Govt. of India. 2013 : CSIR-NET LS, Council of Scientific and Industrial Research (CSIR). Govt. of India.

PUBLICATIONS:
Andrew Bellaart, Amanda Brambila, Jiawei Xu, Francisco Mendez Diaz, Amar Deep, John Anzola, Franz Meitinger, Midori Ohta, Kevin   D Corbett, Arshad Desai and others. TRIM37 prevents ectopic spindle pole assembly by peptide motif recognition and substrate-dependent oligomerization. Nature Structural & Molecular Biology , pages 1–12, 2025. Biswajit Pradhan*, Amar Deep*, Jessica König, Martin   D Baaske, Kevin   D Corbett and Eugene Kim. Loop-extrusion-mediated plasmid DNA cleavage by the bacterial SMC Wadjet complex. Molecular Cell 85(1):107–116, 2025. Emily   G Armbruster, Phoolwanti Rani, Jina Lee, Niklas Klusch, Joshua Hutchings, Lizbeth   Y Hoffman, Hannah Buschkaemper, Eray Enustun, Benjamin   A Adler, Koe Inlow and others. Sequential membrane-and protein-bound organelles compartmentalize genomes during phage infection. Cell Host & Microbe , 2025. Yajie Gu, Huan Li, Amar Deep, Eray Enustun, Dapeng Zhang and Kevin   D Corbett. Bacterial Shedu immune nucleases share a common enzymatic core regulated by diverse sensor domains. Molecular Cell , 2025. Emily   G Armbruster, Phoolwanti Rani, Jina Lee, Niklas Klusch, Joshua Hutchings, Lizbeth   Y Hoffman, Hannah Buschkaemper, Eray Enustun, Benjamin   A Adler, Koe Inlow and others. A transcriptionally active lipid vesicle encloses the injected Chimalliviridae genome in early infection. bioRxiv , pages 2023–09, 2024. Amar Deep, Qishan Liang, Eray Enustun, Joe Pogliano and Kevin   D Corbett. Architecture and activation mechanism of the bacterial PARIS defence system. Nature 634(8033):432–439, 2024. Jack Houston, Clémence Vissotsky, Amar Deep, Hiro Hakozaki, Enice Crews, Karen Oegema, Kevin   D Corbett, Pablo Lara-Gonzalez, Taekyung Kim and Arshad Desai. Phospho-KNL-1 recognition by a TPR domain targets the BUB-1/BUB-3 complex to C. elegans kinetochores. Journal of Cell Biology 223(7):e202402036, 2024. Eray Enustun, Amar Deep, Yajie Gu, Katrina   T Nguyen, Vorrapon Chaikeeratisak, Emily Armbruster, Majid Ghassemian, Elizabeth Villa, Joe Pogliano and Kevin   D Corbett. Identification of the bacteriophage nucleus protein interaction network. Nature Structural & Molecular Biology 30:1653–1662, 2023. Amar Deep*, Latika Singh*, Japleen Kaur*, Maheshwaran Velusamy, Pushpanjali Bhardwaj, Ramandeep Singh and Krishan Gopal Thakur. Structural insights into DarT toxin neutralization by cognate DarG antitoxin: ssDNA mimicry by DarG C-terminal domain keeps the DarT toxin inhibited. Structure 31(7):780–789, 2023. Jack Houston, Midori Ohta, Sebastián   J Gómez-Cavazos, Amar Deep, Kevin   D Corbett, Karen Oegema, Pablo Lara-Gonzalez, Taekyung Kim and Arshad Desai. BUB-1-bound PLK-1 directs CDC-20 kinetochore recruitment to ensure timely embryonic mitoses. Current Biology 33(11):2291–2299, 2023. Thomas   G Laughlin*, Amar Deep*, Amy   M Prichard, Christian Seitz, Yajie Gu, Eray Enustun, Sergey Suslov, Kanika Khanna, Erica   A Birkholz, Emily Armbruster and others. Architecture and self-assembly of the jumbo bacteriophage nuclear shell. Nature 608(7922):429–435, 2022. Amar Deep*, Yajie Gu*, Yong-Qi Gao, Kaori   M Ego, Mark   A Herzik, Huilin Zhou and Kevin   D Corbett. The SMC-family Wadjet complex protects bacteria from plasmid transformation by recognition and cleavage of closed-circular DNA. Molecular Cell 82(21):4145–4159, 2022. Amar Deep, Prabhakar Tiwari, Sakshi Agarwal, Soni Kaundal, Saqib Kidwai, Ramandeep Singh and Krishan   G Thakur. Structural, functional and biological insights into the role of Mycobacterium tuberculosis VapBC11 toxin–antitoxin system: targeting a tRNase to tackle mycobacterial adaptation. Nucleic acids research 46(21):11639–11655, 2018. Amar Deep, Soni Kaundal, Sakshi Agarwal, Ramandeep Singh and Krishan Gopal Thakur. Crystal structure of Mycobacterium tuberculosis VapC20 toxin and its interactions with cognate antitoxin, VapB20, suggest a model for toxin–antitoxin assembly. The FEBS Journal 284(23):4066–4082, 2017. Complete list of publications
RESEARCH AREA:
Molecular and Structural Biology

RESEARCH INTERESTS:

In [99]:
def get_section_text(soup, heading_text):

    # First: try finding it as a tab
    tab = soup.find(
        "a",
        attrs={"data-toggle": "sppb-tab"},
        string=lambda x: x and x.strip().rstrip(":") == heading_text
    )

    if tab:
        target_id = tab.get("href")

        if target_id:
            content = soup.select_one(target_id)

            if content:
                return content.get_text(" ", strip=True)

    # Second: try finding it as a heading
    heading = soup.find(
        lambda tag:
        tag.name in ["h1", "h2", "h3", "h4"]
        and tag.get_text(" ", strip=True).rstrip(":") == heading_text
    )

    if heading:
        parts = []

        for element in heading.find_all_next():

            if (
                element.name in ["h1", "h2", "h3", "h4"]
                and element != heading
            ):
                break

            text = element.get_text(" ", strip=True)

            if text and text.rstrip(":") != heading_text:
                parts.append(text)

        return " ".join(parts).strip() or None

    return None

In [100]:
import time

tab_map = {
    "Research Area": "Research Area",
    "Research Interests": "Research Interests",
    "Career Highlights": "Career Highlights",
    "Awards": "Awards & Recognitions",
    "Publications": "Publications"
}

# Create/reset the columns
for column in tab_map:
    df[column] = None

# Visit every profile
for i, row in df.iterrows():

    profile_url = row["Profile Link"]

    if pd.isna(profile_url):
        continue

    response = requests.get(profile_url)
    profile_soup = BeautifulSoup(response.text, "html.parser")

    for column, website_tab in tab_map.items():

        df.loc[i, column] = get_section_text(
            profile_soup,
            website_tab
        )

    print(i, row["Name"])

    time.sleep(0.3)

print("DONE")

0 Abhik Ganguli
1 Abhishek Chaudhuri
2 Adrene Freeda Dcruz
3 Alok Maharana
4 Ambresh Shivaji
5 Amar Deep
6 Amit Kulshrestha
7 Ananth Venkatesan
8 Angshuman Roy Choudhury
9 Anil Kumar Dasanna
10 Anil Kumar Tripathi
11 Anoop Ambili
12 Anu Sabhlok
13 Arghya Mondal
14 Arijit Kumar De
15 Arunika Mukhopadhaya
16 Arvind
17 Arvind Kumar Shakya
18 Baerbel Sinha
19 Balanarayan Pananghat
20 Chanchal Kumar
21 Chandrakant Sharma Aribam
22 Chandrakanta Ojha
23 Chetan Tukaram Balwe
24 Debashis Adhikari
25 Debdulal Saha
26 Dipanjan Chakraborty
27 Eswaraiah Chakali
28 Goutam Sheet
29 Harvinder Kaur Jassal
30 Hasan Mohammad
31 Indranil Banerjee
32 Jasjeet Singh Bagla
33 Jino George
34 Jogender Singh
35 Jotsaroop Kaur
36 Jyotima Kanaujia
37 Kausik Chattopadhyay
38 Kamal Priya Singh
39 K. P. Yogendran
40 K. R. Shamasundar
41 Kavita Dorai
42 Kinjalk Lochan
43 Krishnendu Gongopadhyay
44 Kritika M. Garg
45 Kuduva R. Vignesh
46 Kuljeet Sandhu
47 Lingaraj Sahu
48 Lolitika Mandal
49 Mahak Sharma
50 Mahender Singh
51 Manabendra Nath Bera
52 Mandip Singh
53 Manjari Jain
54 Manoj Kumar
55 Mihir Sheth
56 N G Prasad
57 Neeraja Sahasrabudhe
58 Pankaj Kushwaha
59 Parth R. Chauhan
60 Philose Koshy
61 Pranab Sardar
62 Prasenjit Das
63 Pritam Mondal
64 Pritika
65 Priyakumari C P
66 Purnananda Guptasarma
67 Ramesh Ramachandran
68 R. Vijaya Anand
69 Rachna Chaba
70 Raj Kumar Roy
71 Rajeev Kapri
72 Rajesh Ramachandran
73 Raju Attada
74 Ram Yadav
75 Ramandeep Singh Johal
76 Ravi Sureshbhai Devani
77 Rhitoban Ray Choudhury
78 Ritajyoti Bandyopadhyay
79 S. S. V. Rama Sastry
80 S. Arulananda babu
81 Sabyasachi Rakshit
82 Sadhan Chandra Das
83 Samarjit Bhattacharyya
84 Samir Kumar Biswas
85 Samrat Ghosh
86 Samrat Mukhopadhyay
87 Sajal Kumar Giri
88 Sanjay Mandal
89 Sanchita Sengupta
90 Sandeep K. Goyal
91 Sanjay Singh
92 Sanjeev Kumar
93 Santanu Kumar Pal
94 Santhosh Kumar Pamula
95 Santosh B. Satbhai
96 Satyajit Jena
97 Shane D'Mello
98 Sharmila Bhattacharya
99 Sharvan Sehrawat
100 Shashi Bhushan Pandit
101 Shravan Kumar Mishra
102 Soma Maity
103 Sourabh Bhattacharya
104 Subhabrata Maiti
105 Sudeshna Sinha
106 Sudip Mandal
107 Sugumar Venkataramani
108 Suman Kumar Barman
109 Sunil A. Patil
110 Tanusree Khandai
111 Tripta Bhatia
112 Ujjal K. Gautam
113 V. Rajesh
114 Vaibhav Vaish
115 Varadharaj Ravi Srinivasan
116 Vidya Devi Negi
117 Vinayak Sinha
118 Vishal Bhardwaj
119 Yashonidhi Pandey
120 Yogesh Singh
121 Yunus Ali Pulpadan
122 Yunus Ali Pulpadan
130 Prof. Sudesh Kaur Khanduja
131 Prof. Kapil Hari Paranjape
DONE

In [104]:
df[
    [
        "Name",
        "Research Area",
        "Research Interests",
        "Career Highlights",
        "Awards",
        "Publications"
    ]
].head(5)

,Name,Research Area,Research Interests,Career Highlights,Awards,Publications
0,Abhik Ganguli,Number Theory,"My research interests are in number theory, pa...","Ph.D., University of Chicago",None,Abhik Ganguli and Suneel Kumar. On the local c...
1,Abhishek Chaudhuri,Condensed Matter Physics: Soft and Biological ...,The aim of our group is to understand the phys...,"Since 2018 : Associate Professor, IISER Mohali...",None,Chamkor Singh and Abhishek Chaudhuri. Anomalou...
2,Adrene Freeda Dcruz,"Science-in-theatre, Media studies, Trauma stud...",I work in the field of Science-in-theatre whic...,"Since 2015 : Assistant Professor, IISER Mohali...",Best Teacher's Award,{bibtex}adrene.bib{/bibtex}
3,Alok Maharana,None,None,None,None,None
4,Ambresh Shivaji,Theoretical High Energy Physics,"Phenomenology of Standard Model and Beyond, Hi...","2016 - 2018 : Postdoctoral Fellow, CP3, Univer...","Member, National Steering Committee, Vigyan Pr...","Mandeep Kaur, Maguni Mahakhud, Ambresh Shivaji..."

In [ ]:

df.to_csv(
    "iisermohali_faculty_complete_raw.csv",
    index=False
)

Done extracting data